server:
  port: 8000
spring:
  application:
    name: project-register
eureka:
  client:
    register-with-eureka: false #表示不注册，做集群是设置成true
    fetch-registry: false #表示不拉取，做集群是设置成true
#    service-url:
#      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true